### ISSUE TITLE
Remove one of the code coverage messages

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/template-python-repository#32]
Currently, PRs provide two code coverage messages; one by Github, one by CodeCov (e.g. https://github.com/cmi-dair/template-python-repository/pull/31). This seems unnecessary. 

I suggest we remove the Github message, as our coverage badge relies on CodeCov. That being said, if there is a way to generate a code coverage badge through Github, I'd be in favor of cutting the number of services we need.

**Comment by nx10** [comment]
Do public repos need CODECOV_TOKEN? Otherwise I would say

if private or CODECOV_TOKEN:
  run_github()
else:
  run_codecov()

**Comment by ReinderVosDeWael** [comment]
They do need the token, yes. I tried it with this, as well as a few variants, but it kept running the github coverage despite the if-statement

```yaml
- name: Pytest coverage comment
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: github.event_name == 'pull_request' && ${{ env.CODECOV_TOKEN == '' }}
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
```
