### ISSUE TITLE
Uniform YAML file extensions

### ISSUE THREAD

**Issue by nx10** [cmi-dair/template-python-repository#68]
YAML files can have either `.yml` or `.yaml` as extensions.

The template repo currently uses both / either in some places (.github/workflows).

The official docs recommend `.yaml`. https://yaml.org/faq.html

Todo:

- use .yaml everywhere

- add this pre-commit hook:

```yaml
  - repo: local
    hooks:
      - id: yaml-file-extension
        name: Check if YAML files has *.yaml extension.
        entry: YAML filenames must have .yaml extension.
        language: fail
        files: .yml$
```
stolen from: https://stackoverflow.com/questions/74638839/force-extension-for-given-file-type-in-a-hook
